#Dockerfile
# Start with a base image containing Java runtime
FROM adoptopenjdk:11-jre-hotspot

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

# The application's jar file
ARG JAR_FILE=target/*.jar

# Add the application's jar to the container
COPY ${JAR_FILE} app.jar

# Run the jar file
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=prod","/app.jar"]