name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]

env:
  dockerImageTag: vartdalen/mvc-java-spring-boot-template:latest
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.6
          architecture: x64
      - name: Maven package
        run: mvn -B package --file ./mvc-java-spring-boot-template-web/pom.xml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build
        run: docker build -t ${{ env.dockerImageTag }} ./mvc-java-spring-boot-template-web/Dockerfile
      - name: Docker push
        run: docker push ${{ env.dockerImageTag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}