name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-push-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.6
          architecture: x64
      - name: Maven package
        run: mvn -B package --file ./mvc-java-spring-boot-template-web/pom.xml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      - name: Docker build
        run: docker build -t vartdalen/mvc-java-spring-boot-template-x64:latest ./mvc-java-spring-boot-template-web/.
      - name: Docker push
        run: docker push vartdalen/mvc-java-spring-boot-template-x64:latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
  build-and-push-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.6
          architecture: x86
      - name: Maven package
        run: mvn -B package --file ./mvc-java-spring-boot-template-web/pom.xml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      - name: Docker build
        run: docker build -t vartdalen/mvc-java-spring-boot-template-x86:latest ./mvc-java-spring-boot-template-web/.
      - name: Docker push
        run: docker push vartdalen/mvc-java-spring-boot-template-x86:latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}