name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.6
          architecture: x64
      - name: Maven package
        run: mvn -B package --file pom.xml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ../../mvc-java-spring-boot-template
          file: ./Dockerfile
          push: true
          tags: secrets.DOCKERHUB_USERNAME/mvc-java-spring-boot-template:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}